### PR TITLE
Fix bug in Ethernet principal

### PR DESCRIPTION
**Pull request by sauravkumar2014**

### CODE REVIEW

**Comment by AltraMayor** [comment]
Hi @sauravkumar2014,

This pull request is trying to add support to the Ethernet principal all over again instead of just fixing the bug you've found. This is what that is causing the conflicts GitHub is pointing out above. Once you address this issue, rename the pull request and commit to what it's actually meant to accomplish.

**Comment by sauravkumar2014** [comment]
Hi @AltraMayor,
I think to resolve this issue what i have to do is add another commit and then issue a pull request but doing so will cause an unnecessary commit. If it is alright, could i have the write access to the main repository to avoid such commits, or i could add another commit for the bug.

**Comment by AltraMayor** [comment]
Git can be complicated, but I think you can solve everything on your side. The general idea is to make sure that your master branch is up to date with my xiaconf repository. Then you rebase the branch in which you are keeping this pull request to your master. During the rebase you can edit the message of the commit as I suggested above, and take away any file that is not needed or solve conflicts if they exist.

**Comment by sauravkumar2014** [comment]
Hi @AltraMayor ,
The conflict has been resolved and the change being made is only the one with the bug.

**Comment by AltraMayor** [comment]
Could you change the title of the commit as well? The current title is "Add support to the Ethernet principal". Once that's done, we are ready to merge this pull request.

**Comment by sauravkumar2014** [comment]
But in my window it is showing "Fix bug in Ethernet principal" as i edited it earlier itself before re-issuing the pull request.

**Comment by AltraMayor** [comment]
Hi @sauravkumar2014, the title of the pull request is "Fix bug in Ethernet principal", but the title of the only commit in this pull request is "Add support to the Ethernet principal". You can see this by scrolling this page up, or at this page:

https://github.com/AltraMayor/xiaconf/pull/10/commits

**Comment by AltraMayor** [comment]
All you need to do is to edit the message of the commit using `git rebase -i HEAD^`, and push it to GitHub.

**Comment by sauravkumar2014** [comment]
Hi @AltraMayor ,
I have made the required changes.

**Comment by AltraMayor** [comment]
Thank you, @sauravkumar2014. Although this pull request is tiny, you did have a chance to sharpen you git skills. These skills are going to help you while mentoring your GSoC student and with future pull requests.

**Pull request merged**
